### ISSUE TITLE
Compile Error while trying to pass arguments to contracts(ERC20, ERC721) constructors

### ISSUE THREAD

**Issue by P1R** [TEAM3EncodeClub/OpenPartyBE#1]
When trying to compile the contracts the OpenParty.sol has an issue with the arguments we pass for the constructors of the contracts, this are the Name and Symbol. I had been traveling but I will check on the issue tonight. But if someone can solve it 

```shell
$ yarn hardhat compile --show-stack-traces

TypeError: Wrong argument count for function call: 2 arguments given but expected 0.
  --> contracts/OpenParty.sol:31:22:
   |
31 |         votesToken = new OPVotes(votesName, votesSymbol);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


TypeError: Wrong argument count for function call: 2 arguments given but expected 0.
  --> contracts/OpenParty.sol:32:22:
   |
32 |         songsToken = new OPSongs(songsName, songsSymbol);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/builtin-tasks/compile.ts:473:15)
    at async Environment._runTaskDefinition (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async OverriddenTaskDefinition._action (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/@typechain/hardhat/src/index.ts:28:30)
    at async Environment._runTaskDefinition (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async Environment.run (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at async SimpleTaskDefinition.action (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/builtin-tasks/compile.ts:1352:63)
    at async Environment._runTaskDefinition (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async Environment.run (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at async SimpleTaskDefinition.action (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/builtin-tasks/compile.ts:1432:7)
    at async Environment._runTaskDefinition (/home/p1r0/Dev/labs/encode-bootcamp/OpenPartyBE/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
 ```

**Comment by P1R** [comment]
Notice that if we remove the parameters at the constructor of OpenParty.sol, and also to the ERC20 and ERC721 the code compiles without issues....

```solidity
    /// @notice Constructor function
    /// @param _purchaseRatio Amount of tokens given per ETH paid
    /// @param _songFee Amount of tokens required for placing a bet that goes for the prize pool
    constructor(
        uint256 _purchaseRatio,
        uint256 _songFee
    ) {
        votesToken = new OPVotes();
        songsToken = new OPSongs();
        purchaseRatio = _purchaseRatio;
        songFee = 1 ether * _songFee / 100;
    }

```

**Comment by danporeda** [comment]
It makes sense because the OPSongs and OPVotes constructors are empty, rather their inherited ERC20 and ERC721 constructors need arguments. I'm not sure what the syntax for this would be, I will try:

votesToken = new OPVotes()(votesName, votesSymbol);
songsToken = new OPSongs()(songsName, songsSymbol);
or
votesToken = new OPVotes()ERC20(votesName, votesSymbol);
songsToken = new OPSongs()ERC721(songsName, songsSymbol);
or
votesToken = new OPVotes((votesName, votesSymbol));
songsToken = new OPSongs((songsName, songsSymbol));
